### ISSUE TITLE
Using flexbox

### ISSUE THREAD

**Issue by martoio** [Mabonzo/prj-rev-bwfs-tea-cozy#2]
You've done a good job of utilizing flexbox in your project, however, I feel it's important to note when to use it and when not to use it (I'm not entirely sure the header needs flexbox). Take a look at [this article](http://brolik.com/blog/when-to-use-flexbox/) for some info on when/where to use flexbox. It's by no means a definitive guide, but it should give you an idea of proper usage. I find that people tend to overuse flexbox and it ends up breaking more things than it fixes.

**Comment by Mabonzo** [comment]
Flex box in the header is how I space the logo and navigation, but I will look into it, thanks!
